baseURL = "https://skylarkelty.github.io/poetry/"
languageCode = "en-us"
title = "Verses and Visions"

[params]
  tagline = "poems for the space between waking and sleep"
  authorline = "est. 2026 - words written under moonlight"

[taxonomies]
  category = "categories"
